import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ weight:['400', '500', '700'],subsets: ["latin"] });

export const metadata = {
  title: {
    default: "Hero NextJS",
    template: "%s | Hero NextJS",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar/>
        <div className="">
        {children}
        </div>
        {/* <footer className="bg-blue-400">
          This is footer
        </footer> */}
      </body>
    </html>
  );
}
